server: server.o main_file.o insert_record.o print.o delete_records.o save.o
	gcc server.o main_file.o insert_record.o print.o delete_records.o save.o -o server

server.o : server.c
	gcc -c server.c

main_file.o : main_file.c
	gcc -c main_file.c

insert_record.o : insert_record.c
	gcc -c insert_record.c

print.o : print.c
	gcc -c print.c

delete_records.o : delete_records.c
	gcc -c delete_records.c

save.o : save.c
	gcc -c save.c



